### ISSUE TITLE
Homework week 1

### ISSUE THREAD

**Issue by kevinmccartney** [eewhy/js-app-dev-week1#1]
Hey Ey! 

Two things I saw on the week 1 homework -

1. Make sure that in `moreCoffee.js`, you are only logging `"Yes, I'll take another cup of coffee"` only if the count is *less than* 3.
2. In `ninetyNineBottles.js`, the while loop is logging out `i`, which isn't being operated on by the `for` loop, so you don't really need it.
3. In `shopping.js`, there are a couple things that you need to look at
    1. Make sure that you're using the `shoppingList` array's length to compare against in the while loop.
    2. Make sure that you're moving items from the `shoppingList` to the `cart` & logging the results from the `cart` for steps 9 & 10.
4. In `accessingObjects.js`, two things I noticed -
    1. On line 49,  make sure that you're logging the second member of the `OSOptions` array, not the whole array.
    2. For the last step, you need to get the student objects who are using `OSX` as their `computer.OS` & put them into an array (if you need some help on this one, we are going to be going over an array method tonight that will make this easier)
5. For `rockpaperscissors.js`, here are a couple of things to look at -
    1. On line 12 & 13 you're incrementing both wins before you've run your `compare` function.
    2. Make sure that you're logging the winner of the game after a player has won 3 rounds.
6. In `email.js`
    1. Make sure that you're getting the names of the mailbox names
    2. Get the emails from the inboxes & log them
    3. Mark an email as sent
    4. Make a `drafts` mailbox & add a draft email to it

Everything else looks great!

**Comment by kevinmccartney** [comment]
Oh, also, remove the commented out code from the end of `rockpaperscissors.js`. It's not going to affect the way your code runs, but it's always a good idea to get rid of unused code when you're done figuring out a solution.

**Comment by eewhy** [comment]
Completed! :)

**Comment by kevinmccartney** [comment]
Awesome, thanks!
